# Stage 1: Build
FROM golang:1.25.6-alpine
WORKDIR /app
RUN apk add --no-cache curl git
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
